#!/usr/bin/env bash
# Debugging skills, Ubuntu container Nginx installation from listening on port 80
# Nginx must be runing, and listening on port 80 of all the servers active IPv4 IPs
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
service nginx restart
