#!/usr/bin/env bash
# This script displays Holberton School 10 times, but for the 9th iteration, displays Holberton School and then hi on a new line
a=0
while [ $a -lt 10 ]
do
	if [[ $a == 8 ]]
	then
		echo "Hi"
	else
		echo Holberton School
	fi
	a=$((a + 1))
done
