#!/usr/bin/env bash
# This script displays Holberton School 10 times, displays bad luck for the 4th loop iteration, dislays good luck ofr the 8th loop iteration, displays Holberton School for the other iterations
a=1
while [ $a -lt 11 ]
do
	if [[ $a == 4 ]]
	then
		echo bad luck
	elif [[ $a == 8 ]]
	then
		echo good luck
	else
		echo Holberton School
	fi
	a=$((a + 1))
done
