#!/usr/bin/env bash
# Displays numbers from 1 to 20 and displays 4 and then bad luck from China for the 4th loop iteration, displays 9 and then bad luck from Japan for the 9th loop iteration, displays 17 and then bad luck from Italy for the 17th loop iteration
a=1
while [ $a -lt 21 ]
do
	if [ $a -eq 4 ] || [ $a -eq 9 ] || [ $a -eq 17 ]
	then
		case $a in
			4) echo 4
				echo bad luck from China ;;
			9) echo 9
				echo bad luck from Japan ;;
			17) echo 17
				echo bad luck from Italy ;;
		esac
	else
		echo $a
	fi
	a=$((a + 1))
done
