#!/usr/bin/env bash
# This is a script that displays the content of the current directory in a list format where only the part of the name after the first dash is displayed

list=$(ls)
for index in $list
do
	echo "$index" | cut -d '-' -f2
done
